---
title: "edgar_parta"
author: "Gibran Makyanie"
date: "25/04/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_knit$set(root.dir = '/Volumes/Buku Gibran/edgar')

library(tidyverse)
library(edgar)
library(XML)
library(lubridate)
library(tm)
library(RSQLite)
library(tidytext)
library(udpipe)
library(rvest)
```


```{r}
conn <- dbConnect(RSQLite::SQLite(), "edgar.db")
```

```{r}
# ----- TF-IDF Market Level
market_level <- dbGetQuery(conn, 'SELECT year_filed, cleaned_noun FROM master_index')

market_tokens <- market_level %>% 
  unnest_tokens(word, cleaned_noun) %>% 
  count(year_filed, word, sort = TRUE) %>% 
  ungroup() %>%
  bind_tf_idf(word, year_filed, n)
rm(market_level)

market_tokens %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>% group_by(year_filed) %>%
  top_n(20) %>%
  ungroup %>%
  ggplot(aes(word, tf_idf, fill = year_filed)) + geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "tf-idf", title = "Important Terms for S&P 500") +
  facet_wrap(~year_filed, ncol = 4, scales = "free") + coord_flip()

```


```{r}
# ----- Define financial Era
financial_era <- c('Post Financial Crisis (2009 - 2010)', 'CITIS (2011 - 2012)', 'SICAD (2014 - 2015) ', 'Brexit (2016 - 2019)', 'TCJA (2018 - 2019)') 
years <- c('2009,2010', '2011,2012', '2014,2015', '2016,2017,2018,2019', '2018,2019')

for (era in 1:length(financial_era)) {

  gics_level <- dbGetQuery(conn, paste0('SELECT gics_sector, cleaned_noun FROM sp500 LEFT JOIN master_index ON master_index.cik =  sp500.cik 
                             WHERE year_filed IN (', years[era],')'))
  
  # ----- Calculate TF-IDF by sector on a financial era
  gics_tokens <- gics_level %>% 
    unnest_tokens(word, cleaned_noun) %>% 
    count(gics_sector, word, sort = TRUE) %>% 
    ungroup() %>%
    bind_tf_idf(word, gics_sector, n)
  rm(gics_level)
  
  # ----- Plot the important terms
  gics_tokens %>%
    arrange(desc(tf_idf)) %>%
    mutate(word = factor(word, levels = rev(unique(word)))) %>% group_by(gics_sector) %>%
    top_n(20) %>%
    ungroup %>%
    ggplot(aes(word, tf_idf, fill = gics_sector)) + geom_col(show.legend = FALSE) +
    labs(x = NULL, y = "tf-idf", title = paste("Important Terms", financial_era[era]), subtitle = "grouped by GICS sector") +
    
    facet_wrap(~gics_sector, ncol = 4, scales = "free") + coord_flip()

}
```


```{r}
dbDisconnect(conn)
```


